### ISSUE TITLE
Please add Bluetooth driver 

### ISSUE THREAD

**Issue by sinoyster** [SamHGA/HP-EliteBook-2570p-OpenCore-EFI#1]
Please add Bluetooth driver support for the Bluetooth device of hp 2570p ([0a5c:21e1] 20702A1 non-UHE HP SoftSailing)in the BrcmPatchRAM support list.
https://github.com/acidanthera/BrcmPatchRAM

**Comment by sinoyster** [comment]
Please add the kexts in the following order:

BlueToolFixup.kext
BrcmFirmwareData.kext
BrcmPatchRAM3.kext

After that, the Bluetooth will work correctly.

**Comment by SamHGA** [comment]
I will not be adding any new kexts for different hardware, only the hardware I have on my device. The README literally says you need to modify kexts on your own if you have different hardware than what I have.
